<%@ Page Title="" Language="C#" MasterPageFile="~/site.Master" AutoEventWireup="true" CodeBehind="AboutUs.aspx.cs" Inherits="WebApplication1.AboutUs" %>

<asp:Content ContentPlaceHolderID="contentplaceholder1" runat="server">
    <div>

        <asp:TextBox ID="TextBox1" runat="server" style="align-content:space-between" Height="1034px" ReadOnly="True" TextMode="MultiLine" Width="448px" BackColor="White" OnTextChanged="TextBox1_TextChanged">Conference Registration systems allows users to register for the conference to submit their papers. There are two types of users in the system, one is the administrator and the other is the conference user. The project includes features like user sign up, where the user has to register himself for the conference as a student or regular or none, for tutorials only. The student can register for submitting the papers and tutorials in which they want to participate for a flat fee and the extra cost of each paper. Regular registration allows registering the users for the tutorials they want to participate without the privilege of a cheaper rate and no paper submission, the user can only register for the tutorial for a flat rate. The user that wish to register as none does not have any registration fee, they only pay for the tutorials they want to participate. The user can also change his registration type after he logs into the system. He can add additional papers and tutorials. The payment page allows user to pay for the registered papers and tutorials. The user can view or Edit his profile anytime after he logs into the system. If the user wants to register after the due date, he has to pay a late fee. The administrator has a separate homepage where he can view or edit the profile. Additionally, he can get the statistics about the number of papers registered, number of users registered, number of users registered for particular tutorials. Administrator can also export the database to the Excel file from his homepage. The admin has a feature to deduct/override the late fee for a particular user from paying late fee even if the user registers after the due date. Furthermore, the admisnitrator can also export the database log and view the application log.</asp:TextBox>

    </div>
   </asp:Content>
